In [215]:
import numpy as np

# The Basics

In [216]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [217]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [218]:
# get Dimension
a.ndim

1

In [219]:
# Get Shape
b.shape

(2, 3)

In [220]:
# Get Type
a.dtype

dtype('int32')

In [221]:
# Get Size
a.itemsize

4

In [222]:
# Get total size
# a.size
a.itemsize

4

## Accessing/Changing specific elements, rows, columns, etc

In [223]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [224]:
# Get a specific element [r, c]
print(a[1, 2])
print(a[1][2])
print(a[1, -5])

10
10
10


In [225]:
# Get a specific row
a[0, :]

# Get a specific column
a[: , 2]

array([ 3, 10])

In [226]:
# Getting a little more fancy [start:index:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [227]:
a[1,5] = 20
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


## 3-D Example

In [228]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [229]:
# Get specific element (work outside in)
b[0,1,1]

4

In [230]:
# replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## Initialising Different Types of Arrays

In [231]:
# All 0s martix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [232]:
# All 1s martix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [233]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [234]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [235]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [236]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.12012959, 0.70512523],
       [0.55597302, 0.55035821],
       [0.08593143, 0.94000968],
       [0.1569302 , 0.90781058]])

In [237]:
# Random integer Values
np.random.randint(4,7, size=(3,3))

array([[4, 5, 4],
       [6, 4, 4],
       [6, 5, 6]])

In [238]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [239]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [240]:
# Exercise
# [[1,1,1,1,1],[1,0,0,0,1],[1,0,9,0,1],[1,0,0,0,1],[1,1,1,1,1]]
arr = np.ones((5,5), dtype='int32')
zeroarray = np.zeros((3,3))
zeroarray[1, 1] = 9
arr[1:4,1:4] = zeroarray
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


Be careful when copying arrays!!!

In [241]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


## Basic Mathematics

In [242]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [243]:
a + 2

array([3, 4, 5, 6])

In [244]:
a - 2

array([-1,  0,  1,  2])

In [245]:
a * 2

array([2, 4, 6, 8])

In [246]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [247]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [248]:
a ** 2

array([ 1,  4,  9, 16])

In [249]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

## Linear Algebra

In [250]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [251]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [252]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

## Statistics

In [253]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [254]:
np.min(stats)

1

In [255]:
np.max(stats, axis=1)

array([3, 6])

In [256]:
np.sum(stats, axis=0)

array([5, 7, 9])

## Reorganising Arrays

In [257]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [258]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [259]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Load Data from File

In [260]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


## Boolean Masking and Advanced Indexing

In [261]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [262]:
## You can index with a lsit in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [263]:
## Answer to Exercise 2
array = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(array[2:4, 0:2])
print(array[[0,1,2,3],[1,2,3,4]])
print(array[[0,4,5],3:])

[[11 12]
 [16 17]]
[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [29 30]]
