In [7]:
import numpy as np

# The Basics

In [8]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [9]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [10]:
# get Dimension
a.ndim

1

In [11]:
# Get Shape
b.shape

(2, 3)

In [12]:
# Get Type
a.dtype

dtype('int64')

In [15]:
# Get Size
a.itemsize

8

In [16]:
# Get total size
# a.size
a.itemsize

3

## Accessing/Changing specific elements, rows, columns, etc

In [18]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [24]:
# Get a specific element [r, c]
print(a[1, 2])
print(a[1][2])
print(a[1, -5])

10
10
10


In [25]:
# Get a specific row
a[0, :]

# Get a specific column
a[: , 2]

array([ 3, 10])

In [26]:
# Getting a little more fancy [start:index:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [27]:
a[1,5] = 20
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


## 3-D Example

In [29]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [30]:
# Get specific element (work outside in)
b[0,1,1]

4

In [32]:
# replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
